// client/src/components/Tracks.svelte
<script>
  import Top from "./Top.svelte";
  import TrackCard from "./UI/TrackCard.svelte";
  import Loader from "./Loader.svelte";
  import { onMount } from "svelte";
  import { getAllTopTracks } from "../spotify.js";
  import { formatDuration } from "../utils/index.js";

  let currentlyActive = "All time";
  let allTracks;
  let currentTracks;

  const fetchTracks = async () => {
    try {
      const data = await getAllTopTracks();
      allTracks = data;
    } catch (error) {
      console.log(error);
    }
  };

  const toggleSwitch = (e) => {
    if (currentlyActive !== e.detail) {
      currentlyActive = e.detail;
    }
  };

  const toggleItem = (e) => {
    if (e.detail === "All time") {
        currentTracks = allTracks.longTerm;
    }
    if (e.detail === "6 months") {
        currentTracks = allTracks.mediumTerm;
    }
    if (e.detail === "4 weeks") {
        currentTracks = allTracks.shortTerm;
    }
  };

  onMount(() => {
    fetchTracks().then(() => {
        currentTracks = allTracks.longTerm;
    });
    window.scrollTo(0, 0);
  });
</script>

<Top {toggleItem} {toggleSwitch} title="Top Tracks" {currentlyActive}>
  {#if currentTracks}
  {#each currentTracks as track (track.id)}
    <TrackCard
    src={track.album.images[0].url}
    name={track.name}
    link={track.external_urls.spotify}
    duration={formatDuration(track.duration_ms)}
    album={track.album.name}
    artist={track.artists[0].name}
    />
  {/each}
{:else}
  <Loader />
{/if}
</Top>

// client/src/components/Tracks.jsx
import React, { useEffect, useState } from "react";
import Top from "./Top";
import TrackCard from "./UI/TrackCard";
import Loader from "./Loader";
import { getAllTopTracks } from "../spotify.js";
import { formatDuration } from "../utils.js";

function Tracks() {
  const [currentlyActive, setCurrentlyActive] = useState("All time");
  const [allTracks, setAllTracks] = useState(null);
  const [currentTracks, setCurrentTracks] = useState(null);

  const toggleSwitch = (e) => {
    if (currentlyActive !== e.detail) {
      setCurrentlyActive(e.detail);
    }
  };

  const toggleItem = (e) => {
    if (e.detail === "All time") {
      setCurrentTracks(allTracks.longTerm);
    } else if (e.detail === "6 months") {
      setCurrentTracks(allTracks.mediumTerm);
    } else if (e.detail === "4 weeks") {
      setCurrentTracks(allTracks.shortTerm);
    }
  };

  useEffect(() => {
    const fetchTracks = async () => {
      try {
        const data = await getAllTopTracks();
        setAllTracks(data);
        setCurrentTracks(data.longTerm);
      } catch (error) {
        console.log(error);
      }
    };
    fetchTracks();
    window.scrollTo(0, 0);
  }, []);

  return (
    <Top toggleItem={toggleItem} toggleSwitch={toggleSwitch} title="Top Tracks" currentlyActive={currentlyActive}>
      {currentTracks ? (
        currentTracks.map((track) => (
          <TrackCard
            key={track.id}
            src={track.album.images[0].url}
            name={track.name}
            link={track.external_urls.spotify}
            duration={formatDuration(track.duration_ms)}
            album={track.album.name}
            artist={track.artists[0].name}
          />
        ))
      ) : (
        <Loader />
      )}
    </Top>
  );
}

export default Tracks;
